import { Router } from "express";
import {
  approvePengurus,
  listPendingPengurus,
  login,
  register,
  listPendingRegistrationsWithClient as listPendingRegistrations,
  approveRegistrationWithClient as approveRegistration,
} from "../controllers/authController";
import {
  bayarIuran,
  createKasRW,
  createWarga,
  deleteWarga,
  deleteKasRW,
  getBlokWilayah,
  getKasRW,
  getIuranWarga,
  getWargaDetail,
  getWargaList,
  updateWarga,
  updateKasRW,
  getDataPenduduk,
  getMonitoringRonda,
  getDetailRondaBlok,
  getPresensiSummaryBlok,
} from "../controllers/rwController";
import {
  createRwMasjid,
  listRwMasjid,
  updateRwMasjid,
} from "../controllers/rwMasjidController";
import {
  createTransaksiZis,
  deleteTransaksiZis,
  updateTransaksiZis,
  getDashboardZis,
  getRecentTransaksiZis,
  getTransaksiZisList,
  exportRekapMuzaqi,
  exportRekapDistribusi,
  exportKwitansiZis,
  createPencatatanDistribusi,
  getPencatatanDistribusiList,
  updatePencatatanDistribusi,
  deletePencatatanDistribusi,
  updatePengaturanZis,
} from "../controllers/zisController";
import {
  exportMasjidReport,
  exportRwReport,
  getMasjidReport,
  getRwReport,
} from "../controllers/reportController";
import {
  createKasMasjid,
  deleteKasMasjid,
  getKasMasjid,
  updateKasMasjid,
} from "../controllers/kasMasjidController";
import {
  createMasjidShareLink,
  createRwShareLink,
  getPublicSharedDashboard,
  getPublicSharedMuzaqi,
  listMasjidShareLinks,
  listRwShareLinks,
  revokeMasjidShareLink,
  revokeRwShareLink,
} from "../controllers/shareLinkController";
import { cekKodeUnik, exportPublicKwitansi, getMasjidList } from "../controllers/publicController";
import {
  createAnggotaKeluarga,
  getAnggotaKeluargaList,
  updateAnggotaKeluarga,
  deleteAnggotaKeluarga,
} from "../controllers/anggotaKeluargaController";
import {
  createIdentitasWarga,
  getIdentitasWargaList,
  updateIdentitasWarga,
  verifyIdentitasWarga,
  deleteIdentitasWarga,
} from "../controllers/identitasWargaController";
import {
  createCicilanIuran,
  getCicilanIuranList,
  updateCicilanStatus,
  updateCicilanIuran,
  deleteCicilanIuran,
} from "../controllers/cicilanIuranController";
import {
  createPerformaRonda,
  getPerformaRondaList,
  updatePerformaRonda,
  deletePerformaRonda,
} from "../controllers/performaRondaController";
import {
  createLaporanInsiden,
  getLaporanInsidenList,
  updateLaporanInsiden,
  closeLaporanInsiden,
  deleteLaporanInsiden,
  exportLaporanPdf,
  getMonitoringInsidenRw,
} from "../controllers/laporanInsidenController";
import {
  getAuditLogList,
  getAuditLogDetail,
  getAuditStatistics,
} from "../controllers/auditLogController";
import {
  createLaporanInsidenForRt,
  getAuditLogForRt,
  getLaporanInsidenForRt,
  getPerformaRondaForRt,
  resetIuranStatusForRt,
  updateLaporanInsidenForRt,
  deleteLaporanInsidenForRt,
  createWargaForRt,
  getWargaForRt,
  getIuranForRt,
  getIuranHistoryForRt,
  bayarIuranForRt,
  createPerformaRondaForRt,
  updatePerformaRondaForRt,
  deletePerformaRondaForRt,
  getJadwalRondaForRt,
  createJadwalRonda,
  updateJadwalRonda,
  deleteJadwalRonda,
  getPetugasForJadwal,
  addPetugasToJadwal,
  removePetugasFromJadwal,
  markPresenceRonda,
  getPresenceForJadwal,
} from "../controllers/rtController";
import {
  getPengaturanIuranRW,
  getPengaturanIuranHistory,
  upsertPengaturanIuranRW,
} from "../controllers/pengaturanIuranController";
import {
  getKasRT,
  createKasRT,
  updateKasRT,
  deleteKasRT,
  getAllKasRTSummary,
} from "../controllers/kasRTController";
import {
  getSetoranRT,
  submitSetoran,
  getSetoranForRW,
  approveSetoran,
} from "../controllers/setoranIuranController";
import {
  updateKasRTSchema,
} from "../validation/schemas";
import {
  getUserPreference,
  updateUserPreference,
  toggleDarkMode,
  resetPreference,
} from "../controllers/userPreferenceController";
import {
  createBlokWilayah,
  getBlokWilayahList,
  updateBlokWilayah,
  deleteBlokWilayah,
} from "../controllers/blokWilayahController";
import {
  createMasjid,
  getMasjidList as getMasjidFullList,
  getMasjidDetail,
  updateMasjid,
  deleteMasjid,
} from "../controllers/masjidController";
import {
  getDashboardOverview,
  getFinancialSummary,
  getActivityLog,
  getSystemHealth,
  getApprovalQueue,
} from "../controllers/superAdminDashboardController";
import {
  checkApproval,
  checkRole,
  verifyToken,
} from "../middlewares/authMiddleware";
import { upload } from "../middlewares/uploadMiddleware";
import {
  authRateLimit,
  publicRateLimit,
  rwActionRateLimit,
  zisActionRateLimit,
} from "../middlewares/rateLimit";
import {
  validateBody,
  validateParams,
  validateQuery,
  validateNominalPositive,
  validateNumericFields,
} from "../middlewares/validateRequest";
import {
  approvePengurusSchema,
  bayarIuranSchema,
  cekKodeUnikParamsSchema,
  cekKodeUnikQuerySchema,
  createShareLinkSchema,
  createKasMasjidSchema,
  createKasRWSchema,
  createTransaksiZisSchema,
  createWargaSchema,
  getDashboardZisQuerySchema,
  getRecentTransaksiZisQuerySchema,
  getTransaksiZisListQuerySchema,
  transaksiZisParamsSchema,
  updateTransaksiZisSchema,
  exportZisQuerySchema,
  getRwMasjidListQuerySchema,
  exportReportQuerySchema,
  getKasMasjidQuerySchema,
  getIuranWargaQuerySchema,
  getIuranRtQuerySchema,
  getKasRWQuerySchema,
  reportMasjidQuerySchema,
  reportRwQuerySchema,
  shareLinkTokenParamsSchema,
  getWargaListQuerySchema,
  kasRWParamsSchema,
  kasMasjidParamsSchema,
  listPendingPengurusQuerySchema,
  listPendingRegistrationsQuerySchema,
  loginSchema,
  masjidListQuerySchema,
  registerSchema,
  approveRegistrationSchema,
  rwMasjidParamsSchema,
  createRwMasjidSchema,
  updateRwMasjidSchema,
  updateWargaSchema,
  updateKasMasjidSchema,
  wargaParamsSchema,
  updateKasRWSchema,
  createAnggotaKeluargaSchema,
  updateAnggotaKeluargaSchema,
  anggotaKeluargaParamsSchema,
  createIdentitasWargaSchema,
  updateIdentitasWargaSchema,
  identitasWargaParamsSchema,
  createCicilanIuranSchema,
  getCicilanIuranQuerySchema,
  cicilanIuranParamsSchema,
  createPerformaRondaSchema,
  getPerformaRondaQuerySchema,
  updatePerformaRondaSchema,
  performaRondaParamsSchema,
  createLaporanInsidenSchema,
  getLaporanInsidenQuerySchema,
  updateLaporanInsidenSchema,
  laporanInsidenParamsSchema,
  getAuditLogQuerySchema,
  auditLogParamsSchema,
  updateUserPreferenceSchema,
  createBlokWilayahSchema,
  updateBlokWilayahSchema,
  blokWilayahParamsSchema,
  getBlokWilayahQuerySchema,
  createMasjidSchema,
  updateMasjidSchema,
  masjidParamsSchema,
  getMasjidListQuerySchema,
  createRtWargaSchema,
  createRtPerformaRondaSchema,
  getRtPerformaRondaQuerySchema,
  updateRtPerformaRondaSchema,
  rtPerformaRondaParamsSchema,
  createRtLaporanInsidenSchema,
  getRtLaporanInsidenQuerySchema,
  updateRtLaporanInsidenSchema,
  rtLaporanInsidenParamsSchema,
  getRtAuditLogQuerySchema,
  pengaturanIuranRWSchema,
  createKasRTSchema,
  approveSetoranSchema,
  updateCicilanIuranSchema,
} from "../validation/schemas";

const router = Router();

// ==================== AUTH ROUTES ====================
router.post("/auth/register", authRateLimit, validateBody(registerSchema), register);
router.post("/auth/login", authRateLimit, validateBody(loginSchema), login);
router.patch(
  "/auth/approve-pengurus",
  authRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(approvePengurusSchema),
  approvePengurus
);
router.get(
  "/auth/pending-pengurus",
  authRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(listPendingPengurusQuerySchema),
  listPendingPengurus
);
router.get(
  "/auth/pending-registrations",
  authRateLimit,
  verifyToken,
  checkRole(["SUPERADMIN"]),
  checkApproval,
  validateQuery(listPendingRegistrationsQuerySchema),
  listPendingRegistrations
);
router.patch(
  "/auth/approve-registration",
  authRateLimit,
  verifyToken,
  checkRole(["SUPERADMIN"]),
  checkApproval,
  validateBody(approveRegistrationSchema),
  approveRegistration
);

// ==================== WARGA ROUTES ====================
router.post(
  "/rw/warga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateBody(createWargaSchema),
  createWarga
);
router.get(
  "/rw/warga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateQuery(getWargaListQuerySchema),
  getWargaList
);
router.get(
  "/rw/warga/:warga_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(wargaParamsSchema),
  getWargaDetail
);
router.patch(
  "/rw/warga/:warga_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(wargaParamsSchema),
  validateBody(updateWargaSchema),
  updateWarga
);
router.delete(
  "/rw/warga/:warga_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(wargaParamsSchema),
  deleteWarga
);

// ==================== DATA PENDUDUK ROUTES (RW READ-ONLY) ====================
router.get(
  "/rw/data-penduduk",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getDataPenduduk
);

// ==================== ANGGOTA KELUARGA ROUTES ====================
router.post(
  "/rw/anggota-keluarga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(createAnggotaKeluargaSchema),
  createAnggotaKeluarga
);
router.get(
  "/rw/anggota-keluarga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getAnggotaKeluargaList
);
router.patch(
  "/rw/anggota-keluarga/:anggota_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(anggotaKeluargaParamsSchema),
  validateBody(updateAnggotaKeluargaSchema),
  updateAnggotaKeluarga
);
router.delete(
  "/rw/anggota-keluarga/:anggota_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(anggotaKeluargaParamsSchema),
  deleteAnggotaKeluarga
);

// ==================== IDENTITAS WARGA ROUTES ====================
router.post(
  "/rw/identitas-warga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  upload.single("dokumen"),
  validateBody(createIdentitasWargaSchema),
  createIdentitasWarga
);
router.get(
  "/rw/identitas-warga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getIdentitasWargaList
);
router.patch(
  "/rw/identitas-warga/:identitas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  upload.single("dokumen"),
  validateParams(identitasWargaParamsSchema),
  validateBody(updateIdentitasWargaSchema),
  updateIdentitasWarga
);
router.patch(
  "/rw/identitas-warga/:identitas_id/verify",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(identitasWargaParamsSchema),
  verifyIdentitasWarga
);
router.delete(
  "/rw/identitas-warga/:identitas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(identitasWargaParamsSchema),
  deleteIdentitasWarga
);

// ==================== CICILAN IURAN ROUTES ====================
router.post(
  "/rw/cicilan-iuran",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(createCicilanIuranSchema),
  createCicilanIuran
);
router.get(
  "/rw/cicilan-iuran",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(getCicilanIuranQuerySchema),
  getCicilanIuranList
);
router.patch(
  "/rw/cicilan-iuran/:cicilan_id/bayar",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(cicilanIuranParamsSchema),
  updateCicilanStatus
);
router.delete(
  "/rw/cicilan-iuran/:cicilan_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(cicilanIuranParamsSchema),
  deleteCicilanIuran
);
router.post(
  "/rt/cicilan-iuran",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateBody(createCicilanIuranSchema),
  createCicilanIuran
);
router.get(
  "/rt/cicilan-iuran",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateQuery(getCicilanIuranQuerySchema),
  getCicilanIuranList
);
router.patch(
  "/rt/cicilan-iuran/:cicilan_id/bayar",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(cicilanIuranParamsSchema),
  updateCicilanStatus
);
router.delete(
  "/rt/cicilan-iuran/:cicilan_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(cicilanIuranParamsSchema),
  deleteCicilanIuran
);

// ==================== PERFORMA RONDA ROUTES ====================
router.post(
  "/rw/performa-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(createPerformaRondaSchema),
  createPerformaRonda
);
router.get(
  "/rw/performa-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(getPerformaRondaQuerySchema),
  getPerformaRondaList
);
router.patch(
  "/rw/performa-ronda/:performa_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(performaRondaParamsSchema),
  validateBody(updatePerformaRondaSchema),
  updatePerformaRonda
);
router.delete(
  "/rw/performa-ronda/:performa_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(performaRondaParamsSchema),
  deletePerformaRonda
);

// ==================== LAPORAN INSIDEN ROUTES ====================
router.post(
  "/rw/laporan-insiden",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  upload.single("foto_bukti"),
  validateBody(createLaporanInsidenSchema),
  createLaporanInsiden
);
router.get(
  "/rw/laporan-insiden",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(getLaporanInsidenQuerySchema),
  getLaporanInsidenList
);
router.patch(
  "/rw/laporan-insiden/:laporan_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  upload.single("foto_bukti"),
  validateParams(laporanInsidenParamsSchema),
  validateBody(updateLaporanInsidenSchema),
  updateLaporanInsiden
);
router.patch(
  "/rw/laporan-insiden/:laporan_id/close",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(laporanInsidenParamsSchema),
  closeLaporanInsiden
);
router.delete(
  "/rw/laporan-insiden/:laporan_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(laporanInsidenParamsSchema),
  deleteLaporanInsiden
);
router.get(
  "/rw/laporan-insiden/:laporan_id/export-pdf",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(laporanInsidenParamsSchema),
  exportLaporanPdf
);
router.get(
  "/rw/monitoring-laporan",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getMonitoringInsidenRw
);

// ==================== RW MONITORING RONDA (READ-ONLY) ====================
router.get(
  "/rw/monitoring-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getMonitoringRonda
);
router.get(
  "/rw/monitoring-ronda/blok/:blok_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getDetailRondaBlok
);
router.get(
  "/rw/monitoring-ronda/presensi",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getPresensiSummaryBlok
);

// ==================== BLOK WILAYAH ROUTES ====================
router.post(
  "/rw/blok-wilayah",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(createBlokWilayahSchema),
  createBlokWilayah
);
router.get(
  "/rw/blok-wilayah-list",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(getBlokWilayahQuerySchema),
  getBlokWilayahList
);
router.patch(
  "/rw/blok-wilayah/:blok_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(blokWilayahParamsSchema),
  validateBody(updateBlokWilayahSchema),
  updateBlokWilayah
);
router.delete(
  "/rw/blok-wilayah/:blok_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(blokWilayahParamsSchema),
  deleteBlokWilayah
);

// ==================== IURAN ROUTES ====================
router.get(
  "/rw/blok-wilayah",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getBlokWilayah
);
router.get(
  "/rw/iuran-warga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(getIuranWargaQuerySchema),
  getIuranWarga
);
router.get(
  "/rt/iuran",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateQuery(getIuranRtQuerySchema),
  (req, res) => {
    const { getIuranForRt } = require("../controllers/rtController");
    return getIuranForRt(req, res);
  }
);
router.get(
  "/rt/iuran/history",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getIuranHistoryForRt
);
router.get(
  "/rt/warga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getWargaForRt
);
router.post(
  "/rt/warga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateBody(createRtWargaSchema),
  createWargaForRt
);
router.patch(
  "/rt/cicilan-iuran/:cicilan_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(cicilanIuranParamsSchema),
  validateBody(updateCicilanIuranSchema),
  updateCicilanIuran
);
router.get(
  "/rt/anggota-keluarga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getAnggotaKeluargaList
);
router.post(
  "/rt/anggota-keluarga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateBody(createAnggotaKeluargaSchema),
  createAnggotaKeluarga
);
router.patch(
  "/rt/anggota-keluarga/:anggota_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(anggotaKeluargaParamsSchema),
  validateBody(updateAnggotaKeluargaSchema),
  updateAnggotaKeluarga
);
router.delete(
  "/rt/anggota-keluarga/:anggota_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(anggotaKeluargaParamsSchema),
  deleteAnggotaKeluarga
);
router.get(
  "/rt/identitas-warga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getIdentitasWargaList
);
router.post(
  "/rt/identitas-warga",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  upload.single("dokumen"),
  validateBody(createIdentitasWargaSchema),
  createIdentitasWarga
);
router.patch(
  "/rt/identitas-warga/:identitas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  upload.single("dokumen"),
  validateParams(identitasWargaParamsSchema),
  validateBody(updateIdentitasWargaSchema),
  updateIdentitasWarga
);
router.patch(
  "/rt/identitas-warga/:identitas_id/verify",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(identitasWargaParamsSchema),
  verifyIdentitasWarga
);
router.delete(
  "/rt/identitas-warga/:identitas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(identitasWargaParamsSchema),
  deleteIdentitasWarga
);
router.get(
  "/rt/performa-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateQuery(getRtPerformaRondaQuerySchema),
  getPerformaRondaForRt
);
router.post(
  "/rt/performa-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateBody(createRtPerformaRondaSchema),
  createPerformaRondaForRt
);
router.patch(
  "/rt/performa-ronda/:performa_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(rtPerformaRondaParamsSchema),
  validateBody(updateRtPerformaRondaSchema),
  updatePerformaRondaForRt
);
router.delete(
  "/rt/performa-ronda/:performa_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(rtPerformaRondaParamsSchema),
  deletePerformaRondaForRt
);

// JADWAL RONDA ROUTES
router.get(
  "/rt/jadwal-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getJadwalRondaForRt
);
router.post(
  "/rt/jadwal-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  createJadwalRonda
);
router.patch(
  "/rt/jadwal-ronda/:jadwal_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  updateJadwalRonda
);
router.delete(
  "/rt/jadwal-ronda/:jadwal_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  deleteJadwalRonda
);

// RONDA PETUGAS ROUTES
router.get(
  "/rt/jadwal-ronda/:jadwal_id/petugas",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getPetugasForJadwal
);
router.post(
  "/rt/jadwal-ronda/:jadwal_id/petugas",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  addPetugasToJadwal
);
router.delete(
  "/rt/ronda-petugas/:petugas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  removePetugasFromJadwal
);

// PRESENSI RONDA ROUTES
router.post(
  "/rt/jadwal-ronda/:jadwal_id/presensi",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  markPresenceRonda
);
router.get(
  "/rt/jadwal-ronda/:jadwal_id/presensi",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getPresenceForJadwal
);

router.get(
  "/rt/laporan-insiden",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateQuery(getRtLaporanInsidenQuerySchema),
  getLaporanInsidenForRt
);
router.post(
  "/rt/laporan-insiden",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  upload.single("foto_bukti"),
  validateBody(createRtLaporanInsidenSchema),
  createLaporanInsidenForRt
);
router.patch(
  "/rt/laporan-insiden/:laporan_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  upload.single("foto_bukti"),
  validateParams(rtLaporanInsidenParamsSchema),
  validateBody(updateRtLaporanInsidenSchema),
  updateLaporanInsidenForRt
);
router.delete(
  "/rt/laporan-insiden/:laporan_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateParams(rtLaporanInsidenParamsSchema),
  deleteLaporanInsidenForRt
);
router.get(
  "/rt/audit-logs",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateQuery(getRtAuditLogQuerySchema),
  getAuditLogForRt
);
router.patch(
  "/rw/bayar-iuran",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(bayarIuranSchema),
  bayarIuran
);
router.post(
  "/rt/iuran/bayar",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateBody(bayarIuranSchema),
  bayarIuranForRt
);
router.patch(
  "/rt/iuran/reset",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateBody(bayarIuranSchema),
  resetIuranStatusForRt
);

// ==================== PENGATURAN IURAN RW ROUTES ====================
router.get(
  "/rw/pengaturan-iuran",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getPengaturanIuranRW
);
router.get(
  "/rw/pengaturan-iuran/history",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getPengaturanIuranHistory
);
router.post(
  "/rw/pengaturan-iuran",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(pengaturanIuranRWSchema),
  upsertPengaturanIuranRW
);

// ==================== KAS RT ROUTES ====================
router.get(
  "/rt/kas",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT", "RW"]),
  checkApproval,
  getKasRT
);
router.post(
  "/rt/kas",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  validateBody(createKasRTSchema),
  createKasRT
);
router.get(
  "/rw/kas-rt-summary",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getAllKasRTSummary
);

// ==================== SETORAN IURAN RT ROUTES ====================
// ==================== KAS RT ROUTES ====================
router.get(
  "/rt/kas",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT", "RW"]),
  checkApproval,
  getKasRT
);
router.post(
  "/rt/kas",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  upload.single("bukti_foto"),
  validateBody(createKasRTSchema),
  createKasRT
);
router.put(
  "/rt/kas/:kas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  upload.single("bukti_foto"),
  validateBody(updateKasRTSchema),
  updateKasRT
);
router.delete(
  "/rt/kas/:kas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  deleteKasRT
);

// ==================== SETORAN RT TO RW ROUTES ====================
router.get(
  "/rt/setoran",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getSetoranRT
);
router.post(
  "/rt/setoran/submit",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  upload.single("bukti_foto"),
  submitSetoran
);
router.get(
  "/rw/setoran-rt",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getSetoranForRW
);
router.post(
  "/rw/setoran-rt/:setoran_id/approve",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(approveSetoranSchema),
  approveSetoran
);


// ==================== KAS RW ROUTES ====================
router.post(
  "/rw/kas",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  validateNominalPositive(),
  checkApproval,
  upload.single("bukti_foto"),
  validateBody(createKasRWSchema),
  createKasRW
);
router.get(
  "/rw/kas",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(getKasRWQuerySchema),
  getKasRW
);
router.patch(
  "/rw/kas/:kas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  upload.single("bukti_foto"),
  validateParams(kasRWParamsSchema),
  validateBody(updateKasRWSchema),
  updateKasRW
);
router.delete(
  "/rw/kas/:kas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(kasRWParamsSchema),
  deleteKasRW
);

// ==================== RW MASJID ROUTES ====================
router.get(
  "/rw/masjid",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(getRwMasjidListQuerySchema),
  listRwMasjid
);
router.post(
  "/rw/masjid",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(createRwMasjidSchema),
  createRwMasjid
);
router.patch(
  "/rw/masjid/:masjid_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(rwMasjidParamsSchema),
  validateBody(updateRwMasjidSchema),
  updateRwMasjid
);

// ==================== MASJID (FULL CRUD) ROUTES ====================
router.post(
  "/rw/masjid-full",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(createMasjidSchema),
  createMasjid
);
router.get(
  "/rw/masjid-full",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(getMasjidListQuerySchema),
  getMasjidFullList
);
router.get(
  "/rw/masjid-full/:masjid_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(masjidParamsSchema),
  getMasjidDetail
);
router.patch(
  "/rw/masjid-full/:masjid_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(masjidParamsSchema),
  validateBody(updateMasjidSchema),
  updateMasjid
);
router.delete(
  "/rw/masjid-full/:masjid_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(masjidParamsSchema),
  deleteMasjid
);

// ==================== RW REPORTS ROUTES ====================
router.get(
  "/rw/report",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(reportRwQuerySchema),
  getRwReport
);
router.get(
  "/rw/report/export",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateQuery(exportReportQuerySchema),
  exportRwReport
);

// ==================== RW SHARE LINKS ROUTES ====================
router.post(
  "/rw/share-links",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateBody(createShareLinkSchema),
  createRwShareLink
);
router.get(
  "/rw/share-links",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  listRwShareLinks
);
router.patch(
  "/rw/share-links/:token/revoke",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  validateParams(shareLinkTokenParamsSchema),
  revokeRwShareLink
);

// ==================== ZIS TRANSAKSI ROUTES ====================
router.post(
  "/zis/transaksi",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  validateNumericFields(["jumlah_jiwa", "nominal_zakat", "nominal_infaq", "total_beras_kg"]),
  checkApproval,
  validateBody(createTransaksiZisSchema),
  createTransaksiZis
);
router.get(
  "/zis/dashboard",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateQuery(getDashboardZisQuerySchema),
  getDashboardZis
);
router.get(
  "/zis/transaksi",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateQuery(getTransaksiZisListQuerySchema),
  getTransaksiZisList
);
router.get(
  "/zis/transaksi/recent",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateQuery(getRecentTransaksiZisQuerySchema),
  getRecentTransaksiZis
);
router.get(
  "/zis/transaksi/export/muzaqi",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateQuery(exportZisQuerySchema),
  exportRekapMuzaqi
);
router.get(
  "/zis/transaksi/export/distribusi",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateQuery(exportZisQuerySchema),
  exportRekapDistribusi
);
router.get(
  "/zis/transaksi/:transaksi_id/kwitansi",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateParams(transaksiZisParamsSchema),
  exportKwitansiZis
);
router.patch(
  "/zis/transaksi/:transaksi_id",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateParams(transaksiZisParamsSchema),
  validateBody(updateTransaksiZisSchema),
  updateTransaksiZis
);
router.delete(
  "/zis/transaksi/:transaksi_id",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateParams(transaksiZisParamsSchema),
  deleteTransaksiZis
);

// ==================== ZIS DISTRIBUSI ROUTES ====================
router.post(
  "/zis/distribusi",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  createPencatatanDistribusi
);
router.get(
  "/zis/distribusi",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  getPencatatanDistribusiList
);
router.patch(
  "/zis/distribusi/:id",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  updatePencatatanDistribusi
);
router.delete(
  "/zis/distribusi/:id",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  deletePencatatanDistribusi
);

// ==================== ZIS PENGATURAN ROUTES ====================
router.patch(
  "/pengaturan-zis/:id",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  updatePengaturanZis
);

// ==================== MASJID REPORT ROUTES ====================
router.get(
  "/masjid/report",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateQuery(reportMasjidQuerySchema),
  getMasjidReport
);
router.get(
  "/masjid/report/export",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateQuery(exportReportQuerySchema),
  exportMasjidReport
);

// ==================== MASJID SHARE LINKS ROUTES ====================
router.post(
  "/masjid/share-links",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateBody(createShareLinkSchema),
  createMasjidShareLink
);
router.get(
  "/masjid/share-links",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  listMasjidShareLinks
);
router.patch(
  "/masjid/share-links/:token/revoke",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateParams(shareLinkTokenParamsSchema),
  revokeMasjidShareLink
);

// ==================== KAS MASJID ROUTES ====================
router.post(
  "/masjid/kas",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateBody(createKasMasjidSchema),
  createKasMasjid
);
router.get(
  "/masjid/kas",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateQuery(getKasMasjidQuerySchema),
  getKasMasjid
);
router.patch(
  "/masjid/kas/:kas_id",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateParams(kasMasjidParamsSchema),
  validateBody(updateKasMasjidSchema),
  updateKasMasjid
);
router.delete(
  "/masjid/kas/:kas_id",
  zisActionRateLimit,
  verifyToken,
  checkRole(["PENGURUS_MASJID"]),
  checkApproval,
  validateParams(kasMasjidParamsSchema),
  deleteKasMasjid
);

// ==================== USER PREFERENCE ROUTES ====================
router.get(
  "/user/preference",
  rwActionRateLimit,
  verifyToken,
  checkApproval,
  getUserPreference
);
router.patch(
  "/user/preference",
  rwActionRateLimit,
  verifyToken,
  checkApproval,
  validateBody(updateUserPreferenceSchema),
  updateUserPreference
);
router.patch(
  "/user/preference/dark-mode/toggle",
  rwActionRateLimit,
  verifyToken,
  checkApproval,
  toggleDarkMode
);
router.post(
  "/user/preference/reset",
  rwActionRateLimit,
  verifyToken,
  checkApproval,
  resetPreference
);

// ==================== AUDIT LOG ROUTES ====================
router.get(
  "/admin/audit-logs",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW", "SUPERADMIN"]),
  checkApproval,
  validateQuery(getAuditLogQuerySchema),
  getAuditLogList
);
router.get(
  "/admin/audit-logs/:log_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW", "SUPERADMIN"]),
  checkApproval,
  validateParams(auditLogParamsSchema),
  getAuditLogDetail
);
router.get(
  "/admin/audit-logs/statistics",
  rwActionRateLimit,
  verifyToken,
  checkRole(["SUPERADMIN"]),
  checkApproval,
  getAuditStatistics
);

// ==================== SUPERADMIN DASHBOARD ROUTES ====================
router.get(
  "/admin/dashboard/overview",
  rwActionRateLimit,
  verifyToken,
  checkRole(["SUPERADMIN"]),
  checkApproval,
  getDashboardOverview
);
router.get(
  "/admin/dashboard/financial",
  rwActionRateLimit,
  verifyToken,
  checkRole(["SUPERADMIN"]),
  checkApproval,
  getFinancialSummary
);
router.get(
  "/admin/dashboard/activity",
  rwActionRateLimit,
  verifyToken,
  checkRole(["SUPERADMIN"]),
  checkApproval,
  getActivityLog
);
router.get(
  "/admin/dashboard/health",
  rwActionRateLimit,
  verifyToken,
  checkRole(["SUPERADMIN"]),
  checkApproval,
  getSystemHealth
);
router.get(
  "/admin/dashboard/approval-queue",
  rwActionRateLimit,
  verifyToken,
  checkRole(["SUPERADMIN"]),
  checkApproval,
  getApprovalQueue
);

// ==================== RT RONDA MANAGEMENT ====================
router.post(
  "/rt/jadwal-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  createJadwalRonda
);
router.get(
  "/rt/jadwal-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getJadwalRondaForRt
);
// Note: Single jadwal detail, PATCH, and DELETE are handled by the main routes above
/*
router.get(
  "/rt/jadwal-ronda/:jadwal_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getJadwalRonda
);
*/
/*
router.patch(
  "/rt/jadwal-ronda/:jadwal_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  updateJadwalRonda
);
router.delete(
  "/rt/jadwal-ronda/:jadwal_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  deleteJadwalRonda
);
*/
router.post(
  "/rt/jadwal-ronda/:jadwal_id/petugas",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  addPetugasToJadwal
);
router.delete(
  "/rt/ronda-petugas/:petugas_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  removePetugasFromJadwal
);
router.post(
  "/rt/jadwal-ronda/:jadwal_id/presensi",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  markPresenceRonda
);
router.get(
  "/rt/jadwal-ronda/:jadwal_id/presensi",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RT"]),
  checkApproval,
  getPresenceForJadwal
);

// ==================== RW RONDA MONITORING ====================
// TODO: Implement RW monitoring ronda endpoints
/*
router.get(
  "/rw/monitoring-ronda",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getMonitoringRonda
);
router.get(
  "/rw/monitoring-ronda/blok/:blok_id",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getDetailRondaBlok
);
router.get(
  "/rw/monitoring-ronda/presensi/blok",
  rwActionRateLimit,
  verifyToken,
  checkRole(["RW"]),
  checkApproval,
  getPresensiSummaryBlok
);
*/

// ==================== PUBLIC ROUTES ====================
router.get(
  "/public/masjid-list",
  publicRateLimit,
  validateQuery(masjidListQuerySchema),
  getMasjidList
);
router.get(
  "/public/cek-kode/:kode_unik",
  publicRateLimit,
  validateParams(cekKodeUnikParamsSchema),
  validateQuery(cekKodeUnikQuerySchema),
  cekKodeUnik
);
router.get(
  "/public/cek-kode/:kode_unik/export",
  publicRateLimit,
  validateParams(cekKodeUnikParamsSchema),
  exportPublicKwitansi
);
router.get(
  "/public/shared/:token",
  publicRateLimit,
  validateParams(shareLinkTokenParamsSchema),
  getPublicSharedDashboard
);
router.get(
  "/public/shared/:token/muzaqi",
  publicRateLimit,
  validateParams(shareLinkTokenParamsSchema),
  getPublicSharedMuzaqi
);

export default router;

